#!/usr/bin/env python3
"""Hand-curated relevance judgments for the 154 downloaded papers.

Project: reduce Agent cost (e.g. Code Agent) by EVOLVING tools/skills, while
maintaining performance. Judgments are based on reading each paper's extracted
abstract+intro (the _staging/concise/*.md content).

tier:
  core  = evolves tools/skills/prompts/workflows/memory FOR agents (the user's METHOD)
  method= broader self-evolving-agent / experience-memory / skill-library background
  goal  = reduces agent/LLM cost (routing, cascade, context compression, budget, ...)
decision: keep | reject
"""

# slug -> (decision, tier, note)
DECISIONS = {
    # ---- PART 1 ----
    "2410_10762": ("keep", "core", "AFlow: automated agentic workflow generation/optimization; trades cost for performance."),
    "2511_15915": ("keep", "core", "AccelOpt: self-improving agent with optimization memory; explicitly cost-effective via open models."),
    "2501_11425": ("reject", "", "Agent-R: RL self-training of agent policy to reflect; not tool/skill evolution."),
    "2511_10395": ("keep", "core", "AgentEvolver: efficient self-evolving agent system; targets costly/inefficient agent dev."),
    "2510_04618": ("keep", "core", "ACE: contexts as evolving playbooks (accumulate/refine/organize strategies)."),
    "2601_07641": ("keep", "core", "Beyond Static Tools (TTE): test-time tool synthesis/verification/evolution."),
    "2307_16789": ("keep", "method", "ToolLLM: foundational tool-use framework/benchmark (16000+ APIs)."),
    "2601_07055": ("keep", "core", "Dr. Zero: self-evolving search agents without training data."),
    "2601_02695": ("keep", "core", "EvoRoute: experience-driven self-routing for agent cost/latency (Agent System Trilemma). *** closest match to project ***"),
    "2507_19457": ("keep", "core", "GEPA: reflective prompt evolution; outperforms RL on prompt optimization."),
    "2504_06821": ("keep", "core", "ASI Inducing Programmatic Skills: program-based skills; reduces 10-15% steps."),
    "2305_17126": ("keep", "core", "LATM: LLMs as Tool Makers (closed-loop tool creation/caching)."),
    "2511_13646": ("keep", "core", "Live-SWE-agent: software-engineering agents self-evolve on the fly."),
    "2601_21557": ("keep", "core", "MCE: meta context engineering via agentic skill evolution (co-evolving skills)."),
    "2506_11442": ("keep", "core", "ReVeal: self-evolving code agents via reliable self-verification + tool eval."),
    "2509_25140": ("keep", "core", "ReasoningBank: distills reusable reasoning strategies from experience; memory-aware test-time scaling."),
    "2512_17102": ("keep", "core", "SAGE: RL self-improving agent with skill library (Skill-Augmented GRPO)."),
    "2408_03314": ("keep", "goal", "Scaling test-time compute optimally (foundational cost-vs-performance tradeoff)."),
    "2503_16416": ("reject", "", "Survey on Evaluation of LLM-based Agents (evaluation, not method/cost)."),
    "2601_22628": ("reject", "", "TTCS: test-time training (weight updates) for reasoning; not agent tool/skill evolution."),
    "2509_23285": ("keep", "core", "Tool-Light: self-evolved tool-integrated reasoning; tackles excessive tool calls/overthinking."),
    "2510_14253": ("keep", "method", "Agentic self-learning LLMs in search; co-evolving GRM (RL-based)."),
    "2502_18864": ("reject", "", "AI co-scientist: multi-agent scientific discovery application (not method/cost)."),
    "-_emnlp23_large_language_models_can_self-improve": ("reject", "", "LLMs Can Self-Improve: model weight self-improvement (not agent tool/skill)."),
    "2508_07407": ("keep", "method", "Survey: Comprehensive Survey of Self-Evolving AI Agents."),
    "2507_21046": ("keep", "method", "Survey: Self-Evolving Agents (TMLR) — what/when/how/where to evolve."),
    "2404_14387": ("keep", "method", "Survey: Self-Evolution of Large Language Models."),
    "2603_16060": ("keep", "method", "ARISE: hierarchical RL with tiered skill library (Skills Manager/Worker)."),
    "2510_08558": ("reject", "", "Agent Learning via Early Experience: RL training of agents (policy, not tool/skill)."),
    "2604_18292": ("keep", "method", "Agent-World: self-evolving training arena; MCP/tool environments; lifelong learning."),
    "2511_16043": ("keep", "method", "Agent0: self-evolving agents from zero data via tool-integrated reasoning."),
    "2509_04439": ("keep", "method", "ArcMemo: lifelong concept-level memory distilled from reasoning traces."),
    "2511_19304": ("reject", "", "AutoEnv: automated environments for measuring cross-env agent learning (benchmark)."),
    "2407_12821": ("keep", "core", "AutoFlow: automated workflow generation for LLM agents."),
    "2603_01145": ("keep", "core", "AutoSkill: experience-driven lifelong learning via skill self-evolution."),
    "2408_08435": ("keep", "core", "ADAS: automated design of agentic systems (meta agent codes better agents)."),
    "2402_11443": ("reject", "", "Benchmark Self-Evolving: dynamic LLM evaluation framework (benchmark)."),
    "2604_01658": ("keep", "method", "CORAL: autonomous multi-agent evolution for open-ended discovery (code)."),
    "2309_17428": ("keep", "core", "CRAFT: create + retrieve specialized toolsets for LLMs."),
    "2305_11738": ("keep", "method", "CRITIC: self-correct with tool-interactive critiquing."),
    "2310_03714": ("keep", "core", "DSPy: compile declarative LM calls into self-improving pipelines."),
    "2506_18096": ("keep", "method", "Survey: Deep Research Agents — systematic examination & roadmap."),
    "2504_07952": ("keep", "core", "Dynamic Cheatsheet: test-time learning with evolving adaptive memory."),
    "enabling_self-improving_agents_to_learn_at_test_time_with_human-in-the-loop_guid": ("keep", "method", "ARIA: self-improving agents learn at test time w/ human-in-loop; evolving knowledge repo."),
    "2601_16443": ("reject", "", "Endless Terminals: procedural RL environment generation (training infra)."),
    "2601_16489": ("keep", "method", "EvoConfig: self-evolving multi-agent for efficient env config (software eng)."),
    "2510_13220": ("keep", "method", "EvoTest: evolutionary test-time learning for self-improving agentic systems."),
    "2510_16079": ("keep", "core", "EvolveR: self-evolving agents through experience-driven lifecycle."),
    "2509_15194": ("reject", "", "Evolving LMs without Labels (EVOL-RL): label-free RL self-improvement of model."),
    "2603_05860": ("keep", "core", "MACRO: evolving agents via experience-driven self-skill & tool discovery (method transferable)."),
    "2508_08791": ("keep", "method", "Feedback-driven tool-use improvements via automated build envs (RL for tool use)."),
    "2512_02472": ("reject", "", "Guided Self-Evolving LLMs (R-FEW): model self-evolution training."),
    "gödel_agent_a_self-referential_agent_framework_for_recursively_self-improvement_": ("keep", "core", "Gödel Agent: self-referential framework for recursive self-improvement."),
    "2503_00735": ("reject", "", "LADDER: recursive problem-decomposition self-improvement (reasoning, not agent tool/skill)."),
    "llm_agents_making_agent_tools_-_acl_anthology": ("keep", "core", "TOOLMAKER: agents autonomously turn papers-with-code into LLM tools."),
    "2309_03409": ("keep", "core", "OPRO: LLMs as optimizers; prompt optimization (foundational)."),
    "2509_24771": ("reject", "", "LatentEvolve: self-evolving test-time scaling in latent space (model-level)."),
    "2603_09206": ("reject", "", "MM-Zero: zero-data self-evolution of VLMs (model training)."),
    "2512_18746": ("keep", "core", "MemEvolve: meta-evolution of agent memory systems (jointly evolves memory arch)."),
    "2509_24704": ("keep", "method", "MemGen: generative latent memory for self-evolving agents."),
    "2601_03192": ("keep", "method", "MemRL: self-evolving agents via runtime RL on episodic memory."),
    "2602_02474": ("keep", "core", "MemSkill: learning & evolving memory skills (learnable memory routines)."),
    "mot_memory-of-thought_enables_chatgpt_to_self-improve_-_acl_anthology": ("keep", "method", "MoT: Memory-of-Thought enables self-improvement (external memory)."),
    "2502_02533": ("keep", "core", "Multi-Agent Design: optimizing agent prompts + topologies (Mass)."),
    "2510_23595": ("keep", "method", "Multi-Agent Evolve: LLM self-improve through co-evolution."),
    "2508_05004": ("reject", "", "R-Zero: self-evolving reasoning LLM from zero data (model training)."),
    "2512_10696": ("keep", "core", "ReMe: dynamic procedural memory; reduces redundant trial-and-error."),
    "2603_08561": ("keep", "method", "RetroAgent: evolving via retrospective dual intrinsic feedback."),
    "2509_09498": ("keep", "method", "SEDM: scalable self-evolving distributed memory for agents."),
    "2310_00533": ("reject", "", "SELF: self-evolution with language feedback (model weight)."),
    "2509_06283": ("reject", "", "SFR-DeepResearch: RL training of autonomous single agent."),
    "2512_04797": ("reject", "", "SIMA 2: generalist embodied agent tech report."),
    "2509_23863": ("reject", "", "SPELL: self-play RL for long-context LMs (model training)."),
    "2511_03773": ("keep", "method", "Scaling Agent Learning via Experience Synthesis (DreamGym)."),
    "2602_01966": ("keep", "core", "Self-Consolidation: consolidates experience, cuts retrieval time/noise."),
    "2602_08234": ("keep", "core", "SkillRL: recursive skill-augmented RL with hierarchical SKILLBANK."),
    "2504_07079": ("keep", "core", "SkillWeaver: web agents self-improve by discovering & honing skills (as APIs)."),
    "2602_12670": ("reject", "", "SkillsBench: benchmarking agent skills (benchmark)."),
    # ---- PART 2 ----
    "2509_24726": ("keep", "method", "Socratic-Zero: data-free agent co-evolution (Teacher/Solver/Generator)."),
    "2509_22558": ("reject", "", "StepORLM: self-evolving for Operations-Research models (domain-specific)."),
    "2404_03683": ("reject", "", "Stream of Search: teaching LMs to search (reasoning training)."),
    "2507_00075": ("reject", "", "Theoretical modeling of self-improvement training dynamics (theory)."),
    "toward_self-improvement_of_llms_via_imagination_searching_and_criticizing": ("reject", "", "AlphaLLM: MCTS+LLM self-improvement (model reasoning)."),
    "2305_16291": ("keep", "core", "Voyager: open-ended embodied agent with ever-growing skill library + auto curriculum (foundational)."),
    "2411_02337": ("keep", "method", "WebRL: self-evolving online curriculum RL for web agents; notes expensive APIs."),
    "2401_13919": ("reject", "", "WebVoyager: end-to-end web agent + benchmark."),
    "2506_14234": ("keep", "method", "Xolver: training-free multi-agent reasoning w/ holistic experience learning."),
    "2509_26354": ("keep", "method", "Your Agent May Misevolve: risks across model/memory/tool/workflow evolution pathways."),
    "2406_16937": ("reject", "", "Survey of LLM-based chatbots (off-topic)."),
    "2307_06435": ("reject", "", "Comprehensive Overview of LLMs (general overview)."),
    "2402_09727": ("keep", "goal", "ReadAgent: gist memory compresses context ~20x for long-context agents."),
    "2401_08092": ("keep", "goal", "Survey: Resource-efficient LLM & Multimodal Foundation Models."),
    "2404_14294": ("keep", "goal", "Survey: Efficient Inference for Large Language Models."),
    "2403_16971": ("keep", "goal", "AIOS: LLM agent OS — scheduling/resource/context/memory management for agents."),
    "2010_03768": ("reject", "", "ALFWorld: benchmark environment (not method/cost)."),
    "2507_06229": ("keep", "method", "Agent KB: universal memory for cross-framework experience sharing."),
    "2407_01489": ("keep", "goal", "Agentless: simpler-than-agents approach to SE (cost/complexity argument)."),
    "2512_22857": ("reject", "", "AutoForge: automated environment synthesis for agentic RL (training)."),
    "2310_12963": ("keep", "goal", "AutoMix: route queries to larger LMs to optimize cost (self-verification router)."),
    "2402_02057": ("reject", "", "Lookahead Decoding: decoding acceleration (infra)."),
    "2510_05520": ("keep", "method", "CAM: constructivist agentic memory for long-doc reading."),
    "2308_07201": ("reject", "", "ChatEval: LLM evaluators via multi-agent debate (evaluation)."),
    "2410_16670": ("keep", "method", "CoPS: cross-task experience sharing for sequential reasoning agents."),
    "2303_04673": ("keep", "goal", "EcoOptiGen: cost-effective HPO for LLM inference (budget-aware)."),
    "2509_10446": ("reject", "", "DeepDive: RL training of deep search agents."),
    "2509_25454": ("reject", "", "DeepSearch: MCTS embedded into RLVR training."),
    "2412_19437": ("reject", "", "DeepSeek-V3 technical report (model)."),
    "2510_10197": ("keep", "method", "Don't Just Fine-tune the Agent, Tune the Environment (env tuning paradigm)."),
    "2501_09891": ("keep", "goal", "Mind Evolution: evolutionary search for test-time compute; controls for inference cost."),
    "2404_15182": ("reject", "", "FLoRA: federated parameter-efficient VLM training (off-topic)."),
    "2406_12295": ("reject", "", "Fast & Slow Generating: large/small collaborative decoding (infra)."),
    "2305_05176": ("keep", "goal", "FrugalGPT: LLM cascade to reduce cost up to 98% while matching performance. *** goal landmark ***"),
    "2403_05530": ("reject", "", "Gemini 1.5 technical report (model)."),
    "2505_17716": ("keep", "goal", "AgentRR: record & replay for agents (reliability/privacy/cost/performance)."),
    "2412_19925": ("reject", "", "HADES: hardware speculative decoding (infra)."),
    "2508_08088": ("reject", "", "HierSearch: hierarchical RL training of deep search (training)."),
    "2404_14618": ("keep", "goal", "Hybrid LLM: cost-efficient quality-aware query routing (40% fewer large-model calls)."),
    "2407_21787": ("keep", "goal", "Large Language Monkeys: scaling inference compute via repeated sampling (cost-coverage)."),
    "2511_20639": ("keep", "goal", "LatentMAS: latent collaboration in MAS — fewer tokens, faster inference."),
    "2510_18866": ("keep", "goal", "LightMem: lightweight & efficient memory-augmented generation."),
    "2404_02060": ("reject", "", "LongICLBench: long in-context learning benchmark."),
    "2312_14424": ("reject", "", "Lost in the Logistical Funhouse (humanities/media, off-topic)."),
    "2504_16129": ("reject", "", "MARFT: multi-agent reinforcement fine-tuning framework (training)."),
    "2503_03686": ("keep", "goal", "MAS-GPT: train LLM to build MAS in a single inference (cuts inference cost)."),
    "1909_08053": ("reject", "", "Megatron-LM: training infra (model parallelism)."),
    "2509_25911": ("keep", "method", "Mem-α: learning memory construction via RL."),
    "2504_19413": ("keep", "method", "Mem0: production-ready scalable long-term memory for agents."),
    "2510_12635": ("keep", "goal", "MemAct: memory-as-action context curation for long-horizon efficiency."),
    "2407_06089": ("reject", "", "Merge/Ensemble/Cooperate survey (general collaborative-LLM survey)."),
    "2402_09748": ("reject", "", "Model Compression & Efficient Inference survey (quant/prune/distill infra)."),
    "2502_04180": ("keep", "goal", "MaAS: multi-agent architecture search via supernet; query-dependent resource & token allocation."),
    "2405_11143": ("reject", "", "OpenRLHF: RLHF/RLVR training framework (infra)."),
    "2401_05459": ("keep", "goal", "Survey: Personal LLM Agents — capability, efficiency, security."),
    "2410_11305": ("reject", "", "QSpec: speculative decoding + quantization (infra)."),
    "2307_08621": ("reject", "", "Retentive Network: model architecture (infra)."),
    "2401_11641": ("reject", "", "Revolutionizing Finance with LLMs (application survey)."),
    "2406_18665": ("keep", "goal", "RouteLLM: learning to route LLMs; >2x cost reduction, no quality loss. *** goal landmark ***"),
    "2403_12031": ("keep", "goal", "RouterBench: benchmark for multi-LLM routing systems (cost-vs-quality)."),
    "2405_15793": ("keep", "goal", "SWE-agent: agent-computer interfaces for SE (foundational code agent; interface design)."),
    "swe-bench_can_language_models_resolve_real-world_github_issues": ("reject", "", "SWE-bench: benchmark (evaluation, not method/cost)."),
    "2203_11171": ("reject", "", "Self-Consistency: CoT decoding via sampling (reasoning method, not agent cost)."),
    "2307_15337": ("keep", "goal", "Skeleton-of-Thought: parallel generation to cut end-to-end latency."),
    "2603_04448": ("keep", "core", "SkillNet: create, evaluate, and connect AI skills (skill ecosystem)."),
    "2506_01979": ("reject", "", "SpecBranch: speculative decoding branch parallelism (infra)."),
    "2412_00061": ("reject", "", "Speculative decoding w/ CTC draft model (infra)."),
    "2304_05128": ("keep", "method", "Self-Debug: teaching LLMs to self-debug code (fewer repair iterations)."),
    "2309_17452": ("keep", "method", "ToRA: tool-integrated reasoning agent (tools + language efficiency)."),
    "2506_06579": ("keep", "goal", "Survey: efficient multi-LLM inference — routing & hierarchical techniques."),
    "2402_01742": ("keep", "goal", "Towards Optimizing the Costs of LLM Usage (quality/latency-aware selection)."),
    "2510_08191": ("keep", "core", "Training-Free GRPO: experience as token prior — cost-effective agent enhancement, no param updates."),
    "2304_10891": ("reject", "", "Transformer autonomous-driving compression survey (off-topic)."),
    "2502_08773": ("keep", "goal", "Universal Model Routing (UniRoute): dynamic routing to smallest feasible LLM."),
    "2310_14735": ("reject", "", "Unleashing prompt engineering (general prompt survey)."),
    "2405_05465": ("reject", "", "Vidur: LLM inference simulation framework (infra)."),
    # ---- SUPPLEMENT (landmarks fetched by arxiv-id verification) ----
    "2310_05736": ("keep", "goal", "LLMLingua: prompt compression for accelerated inference (cost landmark)."),
    "2310_06839": ("keep", "goal", "LongLLMLingua: prompt compression in long-context scenarios (cost landmark)."),
    "2308_10144": ("keep", "core", "ExpeL: LLM agents are experiential learners (extracts reusable insights)."),
    "2211_01910": ("keep", "core", "APE: Large Language Models Are Human-Level Prompt Engineers (prompt optimization landmark)."),
    "2602_04837": ("keep", "core", "Group-Evolving Agents: open-ended self-improvement via experience sharing."),
    "2303_11366": ("keep", "method", "Reflexion: language agents with verbal reinforcement (self-reflection)."),
    "2303_17651": ("keep", "method", "Self-Refine: iterative refinement with self-feedback."),
    "2302_04761": ("keep", "method", "Toolformer: LMs teach themselves to use tools (foundational tool use)."),
    "2310_12823": ("reject", "", "AgentTuning: RL fine-tuning of agent abilities (no tool/skill evolution)."),
}
